version: '3'
services:
  todo-container:
    image: thibs12/todolist:latest
    ports:
      - "5000:8080"
    environment:
      - DB_HOST=db
    container_name: todo-container
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: todolist
      MYSQL_USER: thibs
      MYSQL_PASSWORD: password
    container_name: server-sql
  