version: '3'

volumes:
  datafiles:

services:
  db:
    image: mysql:latest
    volumes:
      - datafiles:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: todolist
      MYSQL_USER: thibs
      MYSQL_PASSWORD: password
    container_name: server-sql
  todo-container:
    image: thibs/todolist:latest
    depends_on:
      - db
    restart: always
    ports:
      - "5000:8080"
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: todo-container
  