# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/TodoApi/TodoApi.sln
    - name: Build
      run: dotnet build src/TodoApi/TodoApi.sln
    - name: Test
      run: |
        dotnet test src/TodoApi.UnitTests/TodoApi.UnitTests.csproj
        dotnet test src/TodoApi.IntegrationTests/TodoApi.IntegrationTests.csproj
  lint:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0
        - name: Super-Linter
          uses: super-linter/super-linter@v5.7.2
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: [build-and-test, lint]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

# Trivy scan        
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/thibs12/todolist:${{ github.sha }} ./src/TodoApi
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          severity: 'CRITICAL,HIGH'
          image-ref: 'docker.io/thibs12/todolist:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          
# Build and push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/TodoApi
          file: ./src/TodoApi/Dockerfile
          push: true
          tags: thibs12/todolist:latest

# Continuous Deployment - New deploy ECS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::891377364444:role/limited-github-access-ecr
          aws-region: eu-west-1

      - name: Force new deployment in ECS
        if: github.event_name == 'pull_request'
        env:
          CLUSTER_NAME: arn:aws:ecs:eu-west-1:891377364444:cluster/TL-ECS-cluster
          SERVICE_NAME: app-service
        run: |
          aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --force-new-deployment --region eu-west-1
