# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/TodoApi/TodoApi.sln
    - name: Build
      run: dotnet build src/TodoApi/TodoApi.sln
    - name: Test
      run: |
        dotnet test src/TodoApi.UnitTests/TodoApi.UnitTests.csproj
        dotnet test src/TodoApi.IntegrationTests/TodoApi.IntegrationTests.csproj
  lint:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0
        - name: Super-Linter
          uses: super-linter/super-linter@v5.7.2
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: [build-and-test, lint]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./src/TodoApi
          push: true
          tags: todo
